### ISSUE TITLE
OBSKorgNanokontrol2 unresponsive after SaveReplayBuffer()

### ISSUE THREAD

**Issue by smurphster** [C9Glax/OBSKorgNanokontrol2#11]
Default config. Tried with the button on "toggle" and "momentary" mode. Tried with replay buffer enabled and disabled. Tried while streaming and recording. All scenarios resulted in the following output to the console and the app going unresponsive.
![image](https://user-images.githubusercontent.com/17991510/103469523-e1afd580-4d33-11eb-9962-981756ef123c.png)

**Comment by smurphster** [comment]
Looks like it's actually getting stuck in OBSConnector.cs line 103. The warning pops after that line and the debugger never reaches line 104. I'm no good with websockets. I'm guessing it is waiting for some sort of message back from OBS and it doesn't like this warning.
![image](https://user-images.githubusercontent.com/17991510/103469736-977c2380-4d36-11eb-82ca-dfeaf2cf51be.png)

**Comment by C9Glax** [comment]
Yes that's part of https://github.com/C9Glax/OBS-Websocket-Sharp problem was that the task wouldn't finish. Fixed it now and released the updated .dll
Should work if you replace it
