### ISSUE TITLE
Weird behavior when adjusting OBS audio source volume

### ISSUE THREAD

**Issue by smurphster** [C9Glax/OBSKorgNanokontrol2#12]
It seems your fix for #8 fixed the issue for the volume levels in Windows, but OBS is displaying some strange behavior. If I move a slider, it seems to initially move in the right direction, but then it stops and increments in the opposite direction very slowly. Sometimes it does not stop until it has reached the max or min. If you keep moving it around, the volume in OBS becomes very erratic.

**Comment by C9Glax** [comment]
Latest commit fixed that, had a Stack instead of a Queue...

**Comment by smurphster** [comment]
I'm still having weird issues with the sliders. The first slider you touch seems to work fine. When you start moving a second slider, it doesn't seem correct at all and after a while of moving it up and down, it seems to stop talking to OBS. I can still adjust the Windows playback and recording volumes using the dials.

**Comment by C9Glax** [comment]
Okay the previous issue I could reproduce, this one I can't...
Have you pulled the latest commit?
This one https://github.com/C9Glax/OBSKorgNanokontrol2/commit/2ba939e46148a9ed07ebf5d28890e874b77ff67d fixed it badly and the latest better.

**Comment by C9Glax** [comment]
Okay nevermind! I just recompiled and now I have the same problem!

**Comment by C9Glax** [comment]
`this.obsVolume.Clear();`
Deleted too much in my cleanup...

**Comment by smurphster** [comment]
Seems pretty smooth now.
