### ISSUE TITLE
Old version of WebSocket

### ISSUE THREAD

**Issue by xams0** [C9Glax/OBSKorgNanokontrol2#17]
13:03:21.766: [obs-websocket] [WebSocketServer::onMessage] Client [::ffff:192.168.1.33]:53666 appears to be running a pre-5.0.0 protocol.
13:03:21.767: [obs-websocket] [WebSocketServer::onClose] WebSocket client `[::ffff:192.168.1.33]:53666` has disconnected with code `4010` and reason: You appear to be attempting to connect with the pre-5.0.0 plugin protocol. Check to make sure your client is updated.

**Comment by C9Glax** [comment]
Hooook, 2 years it has been, gonna probably not check this week, but soon when I redo my setup

**Comment by smurphster** [comment]
This hasn't been updated for WebSocket 5.x right? I've been using the 4.x compatible WebSocket plugin:
https://github.com/obsproject/obs-websocket/releases

Of course, OBSKorgNanokontrol2 should be updated to use 5.x, but this works in the meantime.

**Comment by C9Glax** [comment]
Exactly. Working on the new version

**Comment by C9Glax** [comment]
https://github.com/C9Glax/OBSKorgNanokontrol2/releases/tag/v3.0

It should ™️  work
