### ISSUE TITLE
LED doesn't change when Windows device is muted/unmuted

### ISSUE THREAD

**Issue by smurphster** [C9Glax/OBSKorgNanokontrol2#19]
A button press will change the mute state of a Windows audio device, but the LED does not change.

**Comment by smurphster** [comment]
Actually I found the problem but I need to run. I'll fix it later if you don't beat me to it.

**Comment by C9Glax** [comment]
All yours 👍🏼

**Comment by smurphster** [comment]
That should do it!

**Comment by C9Glax** [comment]
Gonna build and upload in a second
