### ISSUE TITLE
Same problem as issue #3

### ISSUE THREAD

**Issue by Churst85** [C9Glax/OBSKorgNanokontrol2#4]
I'm trying to use this but think I must be doing something wrong... I'm quite new to GitHub but have managed to get a few other OBS plugins to work nicely together.

I followed the installer, but initially had the default audio issue, but that step in the console then passed when I set everything to specific audio I/O.

The websocket plugin is working, as I can control my whole session from the OBS android control app.
And I get a notification about this NanoKontrol2 app connecting to the websocket, but then a disconnect soon after with the same error as in issue #3 .

Your last comment in the last bit of exploring issue #3  about the NanoKontrol2 lighting up before it starts made me think my NanoKontrol2 was set up wrong, as it never lights up when running the connection console, but it works in Reaper, and Live without any problems; and changing the various operating modes doesn't seem to solve it. (I've set it to MIDI CC mode in order to work with this?)

**Comment by Churst85** [comment]
Here's the error from the tray launcher
[NanoKontrol2 OBS Error.txt](https://github.com/C9Glax/OBSKorgNanokontrol2/files/5179212/NanoKontrol2.OBS.Error.txt)

And the Console Launcher
![Console Error](https://user-images.githubusercontent.com/70815571/92320611-a2d67100-f01a-11ea-98f0-98c964d257cb.jpg)

**Comment by C9Glax** [comment]
Hey there, sorry to get back to you this late...

Thanks for already providing this much information! You are right, the nanoKontrol should be lighting up once during startup. If it doesn't do that, then the program wasn't able to connect.

Per default only one program is able to access the nanoKontrol, unless you install the custom KORG driver: https://www.korg.com/us/support/download/driver/0/159/3541/

Attached find a zip containing a new .dll which I would like you to replace. (As always compile your own stuff - I commited a change - and don't run .dlls from random people on the internet). 
[nanoKontrol2OBS.zip](https://github.com/C9Glax/OBSKorgNanokontrol2/files/5361122/nanoKontrol2OBS.zip)
