### ISSUE TITLE
System.NullReferenceException: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by smurphster** [C9Glax/OBSKorgNanokontrol2#5]
I've been struggling to get this to work. I started with the pre-compiled version on OBS's web page, then decided to clone the Git repo. I seem to run into the same issue either way. I'll continue trying to debug it myself, but I just thought I'd post this to see if you might know what's going on without much digging. The LEDs on the device do not change while the app runs. It appears to successfully connect to OBSWebSocket.
![image](https://user-images.githubusercontent.com/17991510/103232304-1d980480-4908-11eb-852d-99b62c6cb0b0.png)
![image](https://user-images.githubusercontent.com/17991510/103232357-3a343c80-4908-11eb-96ff-5b3a73fe59af.png)

**Comment by smurphster** [comment]
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=nanoKontrol2OBS
  StackTrace:
   at nanoKontrol2OBS.Kontrol2OBS.SetupNanoController() in C:\Users\devil\source\repos\OBSKorgNanokontrol2\OBSMidi\nanoKontrol2OBS\Kontrol2OBS.cs:line 254
   at nanoKontrol2OBS.Kontrol2OBS.Create() in C:\Users\devil\source\repos\OBSKorgNanokontrol2\OBSMidi\nanoKontrol2OBS\Kontrol2OBS.cs:line 60
   at ConsoleExecutable.Executable..ctor(String url, String password) in C:\Users\devil\source\repos\OBSKorgNanokontrol2\OBSMidi\ConsoleExecutable\Executable.cs:line 15
   at ConsoleExecutable.Executable.Main(String[] args) in C:\Users\devil\source\repos\OBSKorgNanokontrol2\OBSMidi\ConsoleExecutable\Executable.cs:line 72

**Comment by smurphster** [comment]
Lines 253 & 254 should read:
```
            this.nanoController.ToggleLED(this.bindingConfig.GetOutputToEvent(Config.outputevent.windowsmutechanged, SpecialSourceType.desktop1), this.specialSources[SpecialSourceType.desktop1].connected ? this.specialSources[SpecialSourceType.desktop1].windowsDevice.IsMuted() : false);
            this.nanoController.ToggleLED(this.bindingConfig.GetOutputToEvent(Config.outputevent.windowsmutechanged, SpecialSourceType.desktop2), this.specialSources[SpecialSourceType.desktop2].connected ? this.specialSources[SpecialSourceType.desktop2].windowsDevice.IsMuted() : false);

```
This fixed the error I posted above. I am having some other issues but I suspect that they are partially config issues, so I'll play around with it.

**Comment by C9Glax** [comment]
That is of course correct! This is what happens when you copy/paste repetitive code... Thanks!

**Comment by C9Glax** [comment]
I just ran into the same issue even with your fix.. So gonna reopen and see if I can figure out what is going on!

**Comment by C9Glax** [comment]
For me the issue was, that WebSocket does not return a PID for "default" AudioDevices which I use when assigning volumecontrols to the correct slider...
Just pushed the potential fix...

**Comment by smurphster** [comment]
I reset my local copy of your repository. Now it just exits after setting up audio devices. I'm not using the "default" for either desktop audio or capture device. I have my Realtek card selected for desktop audio, and my AT2020USB+ for my mic. No other audio sources. I'll see if I can figure out where it is exiting.

**Comment by smurphster** [comment]
Kontrol2OBS.cs Line 239, you're calling this.Dispose() in a "finally" clause. That's causing it to exit on me. I removed that and it loads properly.

**Comment by C9Glax** [comment]
Yea ':) Figured that out now...
Been a long time since I coded in C#. That statement belonged in the catch-clause...

**Comment by C9Glax** [comment]
Closing if you agree that this issue is fixed

**Comment by smurphster** [comment]
Yes, I haven't had any more issues since that last commit. Thanks for all of your hard work on this!
